# Generated by Django 4.2.5 on 2023-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bucket_images/'),
        ),
    ]
